on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pre:
    runs-on: self-hosted

    container:
      image: docker/compose
      options: "-v \"/home/actions-runnernico/_work\":\"/var/www/stack\":ro,shared"
     
     
    steps:
#     - name: "Container prerequisites"
#       run: |
#         apk add --no-cache git
#     - name: "create file"
#       run: |
#         mkdir -p /var/www/stack
#         echo "this is a test file." > /var/www/stack/test.txt
          
    - name: "Checkout Project"
      uses: actions/checkout@v2
      with:
        clean: false

    - name: "Test"
      run: |
        ls -la /__w/testDocker/testDocker
   
#     - name: "Run [docker-compose build]"
#       run: |
#         docker-compose --log-level INFO up -d --build
    
#     - name: "Test2"
#       run: |
#         docker-compose exec -T php sh -c "ls -all /var/www/stack"
